# Generated by Django 6.1 on 2026-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('period', models.CharField(max_length=7, verbose_name='Период')),
                ('ba_id', models.IntegerField(verbose_name='ID счёта')),
                ('ba_number', models.CharField(max_length=32, verbose_name='Номер счёта')),
                ('account_name', models.CharField(max_length=200, null=True, verbose_name='Счёт')),
                ('bank_name', models.CharField(max_length=500, null=True, verbose_name='Банк')),
                ('currency', models.CharField(max_length=5, null=True, verbose_name='Валюта')),
                ('rate_prev', models.FloatField(null=True, verbose_name='Курс вчера')),
                ('rate', models.FloatField(null=True, verbose_name='Курс')),
                ('base_bb', models.FloatField(null=True, verbose_name='Остаток на начало (вал.)')),
                ('base_dt', models.FloatField(null=True, verbose_name='Приход (вал.)')),
                ('base_cr', models.FloatField(null=True, verbose_name='Расход (вал.)')),
                ('base_eb', models.FloatField(null=True, verbose_name='Остаток на конец (вал.)')),
                ('bb_rub', models.FloatField(null=True, verbose_name='Остаток на начало, ₽')),
                ('dt_rub', models.FloatField(null=True, verbose_name='Приход, ₽')),
                ('cr_rub', models.FloatField(null=True, verbose_name='Расход, ₽')),
                ('fx_diff_rub', models.FloatField(null=True, verbose_name='Курсовая, ₽')),
                ('eb_rub', models.FloatField(null=True, verbose_name='Остаток на конец, ₽')),
            ],
            options={
                'verbose_name': 'Остаток за день',
                'verbose_name_plural': 'Остатки по дням',
                'db_table': 'dashboard_cash_balance',
                'ordering': ['-date', 'ba_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_id', models.IntegerField(verbose_name='ID счёта')),
                ('ba_number', models.CharField(max_length=32, verbose_name='Номер счёта')),
                ('account_name', models.CharField(max_length=200, null=True, verbose_name='Счёт')),
                ('bank_name', models.CharField(max_length=500, null=True, verbose_name='Банк')),
                ('opening_rub', models.FloatField(null=True, verbose_name='Остаток на начало, ₽')),
                ('flows_rub', models.FloatField(null=True, verbose_name='Движение, ₽')),
                ('closing_rub', models.FloatField(null=True, verbose_name='Остаток на конец, ₽')),
                ('diff', models.FloatField(null=True, verbose_name='Расхождение, ₽')),
            ],
            options={
                'verbose_name': 'Сверка счёта',
                'verbose_name_plural': 'Сверка ДДС с остатками',
                'db_table': 'dashboard_cash_check',
                'ordering': ['-diff'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10, verbose_name='Источник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('period', models.CharField(max_length=7, verbose_name='Период')),
                ('ba_id', models.IntegerField(null=True, verbose_name='ID счёта')),
                ('ba_number', models.CharField(max_length=32, null=True, verbose_name='Номер счёта')),
                ('account_name', models.CharField(max_length=200, null=True, verbose_name='Счёт')),
                ('bank_name', models.CharField(max_length=500, null=True, verbose_name='Банк')),
                ('currency', models.CharField(max_length=5, null=True, verbose_name='Валюта')),
                ('line_id', models.IntegerField(null=True, verbose_name='ID строки выписки')),
                ('journal_line_id', models.IntegerField(null=True, verbose_name='ID строки проводки')),
                ('amount_cur', models.FloatField(null=True, verbose_name='Сумма в валюте')),
                ('rate', models.FloatField(null=True, verbose_name='Курс')),
                ('amount_rub', models.FloatField(null=True, verbose_name='Сумма, ₽')),
                ('activity', models.IntegerField(null=True, verbose_name='Код деятельности')),
                ('activity_name', models.CharField(max_length=50, null=True, verbose_name='Деятельность')),
                ('direction', models.IntegerField(null=True, verbose_name='Код направления')),
                ('direction_name', models.CharField(max_length=20, null=True, verbose_name='Направление')),
                ('article_code', models.CharField(max_length=6, null=True, verbose_name='Код статьи')),
                ('article_name', models.CharField(max_length=200, null=True, verbose_name='Статья')),
                ('cf_code', models.CharField(max_length=6, null=True, verbose_name='Код подстатьи')),
                ('cf_name', models.CharField(max_length=200, null=True, verbose_name='Подстатья')),
                ('is_conversion', models.BooleanField(null=True, verbose_name='Конвертация')),
                ('cp_name', models.TextField(null=True, verbose_name='Контрагент')),
                ('inn', models.CharField(max_length=20, null=True, verbose_name='ИНН')),
                ('description', models.TextField(null=True, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Строка ДДС',
                'verbose_name_plural': 'ДДС — строки',
                'db_table': 'dashboard_cash_flow',
                'ordering': ['-date', 'id'],
                'managed': False,
            },
        ),
    ]
