# Generated by Django 6.1 on 2026-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('period', models.CharField(max_length=7, verbose_name='Период')),
                ('accounts', models.IntegerField(verbose_name='Счетов')),
                ('bb_rub', models.FloatField(null=True, verbose_name='Остаток на начало, ₽')),
                ('dt_rub', models.FloatField(null=True, verbose_name='Приход, ₽')),
                ('cr_rub', models.FloatField(null=True, verbose_name='Расход, ₽')),
                ('fx_diff_rub', models.FloatField(null=True, verbose_name='Курсовая, ₽')),
                ('eb_rub', models.FloatField(null=True, verbose_name='Остаток на конец, ₽')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Остатки по дням',
                'db_table': 'dashboard_cash_balance_day',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cashbalance',
            options={'managed': False, 'ordering': ['-date', 'ba_number'], 'verbose_name': 'Остаток за день', 'verbose_name_plural': 'Остатки по счетам за день'},
        ),
    ]
