# Generated by Django 6.1 on 2026-10-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_cashbalanceday_alter_cashbalance_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.IntegerField(verbose_name="ID строки выписки")),
                ("date", models.DateField(null=True, verbose_name="Дата")),
                ("year", models.IntegerField(null=True, verbose_name="Год")),
                ("direction", models.IntegerField(verbose_name="Направление")),
                ("inn", models.CharField(max_length=20, null=True, verbose_name="ИНН")),
                ("cp_name", models.TextField(null=True, verbose_name="Контрагент")),
                ("kbk", models.CharField(max_length=20, null=True, verbose_name="КБК")),
                (
                    "ba_key",
                    models.CharField(
                        max_length=5, null=True, verbose_name="Счёт контрагента, 5 цифр"
                    ),
                ),
                (
                    "ba_number",
                    models.CharField(max_length=32, null=True, verbose_name="Наш счёт"),
                ),
                ("description", models.TextField(null=True, verbose_name="Назначение")),
                ("amount", models.FloatField(null=True, verbose_name="Сумма")),
                (
                    "is_open",
                    models.BooleanField(default=False, verbose_name="Не разнесено"),
                ),
                (
                    "cf_item_id",
                    models.IntegerField(null=True, verbose_name="ID статьи"),
                ),
                (
                    "cf_code",
                    models.CharField(
                        max_length=6, null=True, verbose_name="Код статьи"
                    ),
                ),
                (
                    "cf_name",
                    models.CharField(max_length=200, null=True, verbose_name="Статья"),
                ),
                ("manual", models.BooleanField(default=False, verbose_name="Руками")),
                (
                    "rule_resolver_id",
                    models.IntegerField(null=True, verbose_name="Резолвер правила"),
                ),
                (
                    "rule_kind",
                    models.CharField(
                        max_length=5, null=True, verbose_name="Тип резолвера правила"
                    ),
                ),
                (
                    "kbk_resolver_id",
                    models.IntegerField(null=True, verbose_name="Резолвер КБК"),
                ),
                (
                    "ba_resolver_id",
                    models.IntegerField(null=True, verbose_name="Резолвер счёта"),
                ),
                (
                    "cp_resolver_id",
                    models.IntegerField(
                        null=True, verbose_name="Резолвер контрагента (по ИНН)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрагент и статья",
                "verbose_name_plural": "Контрагенты и статьи",
                "db_table": "dashboard_cp_audit",
                "ordering": ["-date", "id"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="cashcheck",
            options={
                "managed": False,
                "ordering": ["id"],
                "verbose_name": "Сверка счёта",
                "verbose_name_plural": "Сверка с банком",
            },
        ),
    ]
