# Generated by Django 6.1 on 2026-10-05 09:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cp', '0009_gr_delete_cpgroupcompany_and_more'),
        ('macro', '0002_fx_numeric_code_alter_fx_code_alter_fx_name_and_more'),
        ('treasury', '0013_icresolver_alter_resolver_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('kind', models.CharField(choices=[('OPENING', 'Ввод остатков'), ('MANUAL', 'Ручная'), ('AUTO', 'Автомат')], default='MANUAL', max_length=10, verbose_name='Тип')),
                ('description', models.CharField(max_length=500, verbose_name='Содержание')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Журнал проводок',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveSmallIntegerField(choices=[(11, 'Активы'), (12, 'Обязательства'), (13, 'Капитал'), (21, 'Выручка'), (22, 'Прямые расходы'), (23, 'Overheads'), (24, 'SG&A'), (25, 'Прочие доходы и расходы'), (26, 'Финансовые доходы и расходы'), (27, 'Налог на прибыль')], help_text='У субсчёта берётся из счёта', verbose_name='Раздел')),
                ('number', models.PositiveSmallIntegerField(help_text='Счёт: 1–99, субсчёт: 1–999', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Номер')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(editable=False, max_length=7, unique=True, verbose_name='Код')),
                ('nature', models.CharField(choices=[('A', 'Активный'), ('P', 'Пассивный'), ('AP', 'Активно-пассивный')], default='AP', max_length=2, verbose_name='Характер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('bank_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_account', to='treasury.bankaccount', verbose_name='Банковский счёт')),
                ('currency', models.ForeignKey(blank=True, help_text='Пусто — рубли', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_accounts', to='macro.fx', verbose_name='Валюта')),
                ('parent', models.ForeignKey(blank=True, help_text='Заполняется только у субсчёта', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='gl.glaccount', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Дт, ₽')),
                ('cr', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Кт, ₽')),
                ('amount_cur', models.DecimalField(blank=True, decimal_places=2, help_text='Только для валютных счетов, без знака', max_digits=18, null=True, verbose_name='Сумма в валюте')),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Курс')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='gl.glaccount', verbose_name='Счёт')),
                ('cf_item', models.ForeignKey(blank=True, help_text='Для денежных счетов, если это движение денег (не ввод остатка)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='treasury.cfitem', verbose_name='Статья ДДС')),
                ('cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='cp.cp', verbose_name='Контрагент')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gl.journalentry', verbose_name='Проводка')),
            ],
            options={
                'verbose_name': 'Строка проводки',
                'verbose_name_plural': 'Строки проводки',
                'ordering': ['id'],
            },
        ),
    ]
