"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import date
from pathlib import Path
import os
from dotenv import load_dotenv
from django.conf.locale.ru import formats as ru_formats
from django.conf import settings
from .unfold_settings import UNFOLD_SETTINGD
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    "http://37.46.129.233:8085",
]



# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "core",
    "cp",
    "macro",
    "treasury",
    "gl",
    "dashboard",
    # "dashapp.apps.DashappConfig",
    "django_plotly_dash.apps.DjangoPlotlyDashConfig",    
    "django_json_widget",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django_plotly_dash.middleware.BaseMiddleware",
    "django_plotly_dash.middleware.ExternalRedirectionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'

UNFOLD = UNFOLD_SETTINGD

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

X_FRAME_OPTIONS = "SAMEORIGIN"




# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

ru_formats.DECIMAL_SEPARATOR = "."
ru_formats.THOUSAND_SEPARATOR = ","
USE_THOUSAND_SEPARATOR = True
ru_formats.DATE_FORMAT = "d.m.Y"

ru_formats.SHORT_DATE_FORMAT = "d.m.Y"

ru_formats.DATETIME_FORMAT = "d.m.Y H:i"

ru_formats.SHORT_DATETIME_FORMAT = "d.m.Y H:i"

ru_formats.YEAR_MONTH_FORMAT = "m.Y"

ru_formats.MONTH_DAY_FORMAT = "d.m"


STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# MEDIA FILES

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# DEFAULT PRIMARY KEY

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#==============
# Серверные настройки
#==============

SERVER_HOST = os.getenv("SERVER_HOST")

SERVER_USER = os.getenv("SERVER_USER")

SERVER_PASSWORD = os.getenv("SERVER_PASSWORD")

SERVER_MEDIA_PATH = os.getenv("SERVER_MEDIA_PATH")
SERVER_DATA_PARQUET_PATH = os.getenv("SERVER_DATA_PARQUET_PATH")

#==============
# Чеко настройки
#==============

CHECKO_API_KEY = os.environ["CHECKO_API_KEY"]
CHECKO_API_COMPANY_URL = "https://api.checko.ru/v2/company"
CHECKO_API_ENTREPRENEUR_URL = "https://api.checko.ru/v2/entrepreneur"
CHECKO_API_BANK_URL = "https://api.checko.ru/v2/bank"


#==============
# DaData настройки
#==============

DADATA_API_KEY = os.getenv("DADATA_API_KEY", "")

DADATA_SECRET_KEY = os.getenv("DADATA_SECRET_KEY", "")

DADATA_FIND_BY_ID_URL = (
    "https://suggestions.dadata.ru/"
    "suggestions/api/4_1/rs/findById/party"
)


#==============
# Коннекшн стринги
#==============


MYSQL_CON = (
        f"host={os.getenv('DB_HOST')} "
        f"port={os.getenv('DB_PORT', '3306')} "
        f"user={os.getenv('DB_USER')} "
        f"password={os.getenv('DB_PASSWORD')} "
        f"database={os.getenv('DB_NAME')}"
    )

SQLITE_CON = Path(settings.DATABASES["default"]["NAME"]).resolve()


#==============
# Дефолтные пути к файлам проекта
#==============

SQL_FILES_PATH = BASE_DIR / Path("sql")
JSON_FILES_PATH = BASE_DIR / Path("data/json")
PARQUET_FILES_PATH = BASE_DIR / Path("data/parquet")