# Generated by Django 6.1 on 2026-09-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, unique=True, verbose_name='Код ЦБ')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('badge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Бейдж')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
    ]
