# Generated by Django 6.1 on 2026-09-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx',
            name='numeric_code',
            field=models.CharField(default=1, max_length=3, unique=True, verbose_name='Цифровой код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fx',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='fx',
            name='sid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код ЦБ'),
        ),
    ]
