# Generated by Django 6.1 on 2026-09-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=36, unique=True, verbose_name='SID')),
                ('source_file', models.CharField(blank=True, max_length=250, null=True, verbose_name='Файл')),
                ('ba_number', models.CharField(max_length=56, verbose_name='Номер счета')),
                ('date_from', models.DateField(verbose_name='Начало периода')),
                ('date_to', models.DateField(verbose_name='Конец периода')),
                ('bb', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Начальный баланс')),
                ('eb', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Конечный баланс')),
                ('dt', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Поступления')),
                ('cr', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Списания')),
            ],
            options={
                'verbose_name': 'Выписка',
                'verbose_name_plural': 'Выписки',
            },
        ),
    ]
