# Generated by Django 6.1 on 2026-09-18 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0008_cpgroupcompany'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['-date_to', 'ba_number'], 'verbose_name': 'Выписка', 'verbose_name_plural': 'Выписки'},
        ),
        migrations.AddField(
            model_name='statement',
            name='ba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='cp.bankaccount', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='ba_number',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Номер счёта в выписке'),
        ),
    ]
