# Generated by Django 6.1 on 2026-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_bankaccount_bank_is_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='ba_type',
            field=models.CharField(choices=[('MAIN', 'Основной'), ('TRANSIT', 'Транзитный')], default='MAIN', max_length=20, verbose_name='Тип Счета'),
        ),
    ]
