# Generated by Django 6.1 on 2026-10-04 07:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_statement_ba_account_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, 'Операционная'), (2, 'Инвестиционная'), (3, 'Финансовая'), (4, 'Внутригрупповые')], help_text='У подстатьи берётся из статьи', verbose_name='Деятельность')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Поступления'), (2, 'Выплаты')], help_text='У подстатьи берётся из статьи', verbose_name='Направление')),
                ('number', models.PositiveSmallIntegerField(help_text='1–99 внутри своего уровня', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Номер')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(editable=False, max_length=6, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Вместо удаления — выключаем', verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, help_text='Заполняется только у подстатьи', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='treasury.cfitem', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статья ДДС',
                'verbose_name_plural': 'Статьи ДДС',
                'ordering': ['code'],
            },
        ),
    ]
