# Generated by Django 6.1 on 2026-10-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_cfitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_id', models.CharField(help_text='md5 реквизитов операции', max_length=32, unique=True, verbose_name='ID операции')),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид документа')),
                ('doc_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('op_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата операции')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Поступления'), (2, 'Выплаты')], verbose_name='Направление')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма')),
                ('dt', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Поступление')),
                ('cr', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Списание')),
                ('intercompany', models.BooleanField(default=False, verbose_name='Между своими счетами')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН (выписка)')),
                ('inn_adjust', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ИНН')),
                ('cp_name', models.TextField(blank=True, null=True, verbose_name='Контрагент (выписка)')),
                ('cp_ba', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Счёт контрагента')),
                ('cp_bic', models.CharField(blank=True, max_length=20, null=True, verbose_name='БИК контрагента')),
                ('ba_resolver', models.CharField(blank=True, help_text='Первые 5 цифр счёта контрагента', max_length=5, null=True, verbose_name='Резолвер')),
                ('kbk', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='КБК')),
                ('vo_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код валютной операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Назначение платежа')),
                ('desc_pattern', models.TextField(blank=True, help_text='Назначение, где номера, суммы и даты заменены на #', null=True, verbose_name='Шаблон назначения')),
                ('fee_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Комиссия банка')),
                ('fee_withheld', models.BooleanField(default=False, verbose_name='Комиссия удержана')),
                ('debt_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Удержано в счёт долга')),
                ('gross_dt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Оплата покупателя (gross)')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ставка НДС')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма НДС')),
                ('vat_free', models.BooleanField(default=False, verbose_name='Без НДС')),
                ('vat_check', models.BooleanField(blank=True, help_text='Пусто — проверять нечем', null=True, verbose_name='НДС сходится')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Загружено')),
                ('ba_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='treasury.bankaccount', verbose_name='Наш счёт')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='treasury.statement', verbose_name='Выписка')),
            ],
            options={
                'verbose_name': 'Операция по выписке',
                'verbose_name_plural': 'Операции по выпискам',
                'ordering': ['-op_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BSLineAlloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Поступления'), (2, 'Выплаты')], verbose_name='Направление')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма')),
                ('manual', models.BooleanField(default=False, help_text='Правила такую разноску не перезаписывают', verbose_name='Руками')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('cf_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocs', to='treasury.cfitem', verbose_name='Статья ДДС')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocs', to='treasury.bsline', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Разноска',
                'verbose_name_plural': 'Разноска',
            },
        ),
        migrations.AddIndex(
            model_name='bsline',
            index=models.Index(fields=['ba_resolver', 'direction'], name='bsline_resolver_dir'),
        ),
    ]
