# Generated by Django 6.1 on 2026-10-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_bsline_bslinealloc_bsline_bsline_resolver_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.SmallIntegerField(default=0, help_text='Обычно 0. Больше — проверяется раньше остальных', verbose_name='Приоритет')),
                ('ba_prefix', models.CharField(blank=True, help_text='1–5 цифр резолвера: 4, 407, 30233', max_length=5, verbose_name='Счёт контрагента начинается с')),
                ('kbk_prefix', models.CharField(blank=True, help_text='Например 182 (ФНС), 153 (ФТС), 797 (СФР)', max_length=20, verbose_name='КБК начинается с')),
                ('kbk_suffix', models.CharField(blank=True, help_text='510 ЕНП, 110 налог/пошлина, 140 штраф, 160 взносы', max_length=3, verbose_name='КБК заканчивается на')),
                ('vo_prefix', models.CharField(blank=True, help_text='Цифры кода валютной операции: 111 — импорт, 213 — аренда, 010 — конвертация', max_length=5, verbose_name='Код ВО начинается с')),
                ('inn', models.CharField(blank=True, help_text='Один или несколько через запятую', max_length=500, verbose_name='ИНН контрагента')),
                ('intercompany', models.BooleanField(blank=True, help_text='Пусто — не важно', null=True, verbose_name='Между своими счетами')),
                ('text_regex', models.CharField(blank=True, help_text='Регулярное выражение, регистр не важен. Просто слово тоже работает: СБП', max_length=500, verbose_name='Назначение содержит')),
                ('text_exclude', models.CharField(blank=True, help_text='Регулярное выражение', max_length=500, verbose_name='Назначение НЕ содержит')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Строк')),
                ('hits_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Сумма')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний прогон')),
                ('cf_item', models.ForeignKey(help_text='Направление правила = направление статьи', on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='treasury.cfitem', verbose_name='Статья')),
                ('debt_cf_item', models.ForeignKey(blank=True, help_text='Только для поступлений «с уч. гаш. долга»', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_rules', to='treasury.cfitem', verbose_name='Статья для удержанного долга')),
                ('fee_cf_item', models.ForeignKey(blank=True, help_text='Только для поступлений с удержанной комиссией (эквайринг карт)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_rules', to='treasury.cfitem', verbose_name='Статья для удержанной комиссии')),
            ],
            options={
                'verbose_name': 'Правило разноски',
                'verbose_name_plural': 'Правила разноски',
                'ordering': ['-priority', 'cf_item__code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bslinealloc',
            name='rule',
            field=models.ForeignKey(blank=True, help_text='Каким правилом разнесено. Пусто — руками', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocs', to='treasury.cfrule', verbose_name='Правило'),
        ),
    ]
