# Generated by Django 6.1 on 2026-10-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0010_cfrule_bslinealloc_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bslinealloc',
            name='rule',
        ),
        migrations.CreateModel(
            name='Resolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('KBK', 'КБК'), ('BA', 'Счёт контрагента')], max_length=5, verbose_name='Тип')),
                ('key', models.CharField(help_text='КБК или 5 цифр счёта', max_length=20, verbose_name='Ключ')),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Поступления'), (2, 'Выплаты')], verbose_name='Направление')),
                ('payee', models.CharField(blank=True, help_text='Самый частый контрагент в строках', max_length=300, null=True, verbose_name='Получатель / плательщик')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('lines_count', models.PositiveIntegerField(default=0, verbose_name='Строк')),
                ('lines_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Сумма')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Не разнесено, строк')),
                ('open_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Не разнесено, сумма')),
            ],
            options={
                'verbose_name': 'Резолвер',
                'verbose_name_plural': 'Резолверы',
                'ordering': ['-open_amount', '-lines_amount'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'key', 'direction'), name='resolver_kind_key_dir')],
            },
        ),
        migrations.CreateModel(
            name='KbkResolver',
            fields=[
            ],
            options={
                'verbose_name': 'Резолвер КБК',
                'verbose_name_plural': 'Резолверы КБК',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('treasury.resolver',),
        ),
        migrations.CreateModel(
            name='ResolverRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='№')),
                ('text_regex', models.CharField(blank=True, help_text='Регулярка, регистр не важен. Пусто — всё остальное', max_length=500, verbose_name='Назначение содержит')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Строк')),
                ('hits_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Сумма')),
                ('cf_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolver_rules', to='treasury.cfitem', verbose_name='Статья')),
                ('resolver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='treasury.resolver', verbose_name='Резолвер')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bslinealloc',
            name='resolver_rule',
            field=models.ForeignKey(blank=True, help_text='Каким правилом разнесено. Пусто — руками', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocs', to='treasury.resolverrule', verbose_name='Правило'),
        ),
        migrations.DeleteModel(
            name='CFRule',
        ),
    ]
