# Generated by Django 6.1 on 2026-10-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0011_remove_bslinealloc_rule_resolver_kbkresolver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaResolver',
            fields=[
            ],
            options={
                'verbose_name': 'Резолвер счёта',
                'verbose_name_plural': 'Резолверы счетов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('treasury.resolver',),
        ),
        migrations.AddField(
            model_name='resolver',
            name='name',
            field=models.CharField(blank=True, help_text='Для счетов — подсказка по плану счетов ЦБ, можно поправить', max_length=200, null=True, verbose_name='Что за счёт'),
        ),
        migrations.AddField(
            model_name='resolverrule',
            name='debt_cf_item',
            field=models.ForeignKey(blank=True, help_text='«с уч. гаш. долга» — удержано в счёт кредита', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolver_debt_rules', to='treasury.cfitem', verbose_name='Долг → статья'),
        ),
        migrations.AddField(
            model_name='resolverrule',
            name='fee_cf_item',
            field=models.ForeignKey(blank=True, help_text='Удержанная банком комиссия (эквайринг карт)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolver_fee_rules', to='treasury.cfitem', verbose_name='Комиссия → статья'),
        ),
    ]
