# Generated by Django 6.1 on 2026-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0012_baresolver_resolver_name_resolverrule_debt_cf_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcResolver',
            fields=[
            ],
            options={
                'verbose_name': 'Резолвер переводов между своими',
                'verbose_name_plural': 'Резолверы: между своими',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('treasury.resolver',),
        ),
        migrations.AlterField(
            model_name='resolver',
            name='kind',
            field=models.CharField(choices=[('KBK', 'КБК'), ('BA', 'Счёт контрагента'), ('IC', 'Между своими счетами')], max_length=5, verbose_name='Тип'),
        ),
    ]
