# Generated by Django 6.1 on 2026-10-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0013_icresolver_alter_resolver_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolverrule',
            name='debt_cf_item',
        ),
        migrations.RemoveField(
            model_name='resolverrule',
            name='fee_cf_item',
        ),
    ]
