# Generated by Django 6.1 on 2026-10-06 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0014_remove_resolverrule_debt_cf_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsline',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='treasury.statement', verbose_name='Выписка'),
        ),
    ]
