# Generated by Django 6.1 on 2026-10-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0015_alter_bsline_statement"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpResolver",
            fields=[],
            options={
                "verbose_name": "Резолвер контрагента",
                "verbose_name_plural": "Резолверы контрагентов",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("treasury.resolver",),
        ),
        migrations.AddField(
            model_name="resolver",
            name="match_name",
            field=models.CharField(
                blank=True,
                help_text="Только для контрагентов: строки ищутся по названию, а не по ИНН",
                max_length=300,
                null=True,
                verbose_name="Искать по названию",
            ),
        ),
        migrations.AlterField(
            model_name="resolver",
            name="key",
            field=models.CharField(
                help_text="КБК, 5 цифр счёта или ИНН",
                max_length=20,
                verbose_name="Ключ",
            ),
        ),
        migrations.AlterField(
            model_name="resolver",
            name="kind",
            field=models.CharField(
                choices=[
                    ("KBK", "КБК"),
                    ("BA", "Счёт контрагента"),
                    ("IC", "Между своими счетами"),
                    ("CP", "Контрагент"),
                ],
                max_length=5,
                verbose_name="Тип",
            ),
        ),
    ]
