# Generated by Django 6.1 on 2026-09-12 02:46

import cp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ОГРН / ОГРНИП')),
                ('name', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Наименование')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('manager_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Руководитель')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar/', validators=[cp.models.validate_svg], verbose_name='Аватар')),
                ('status', models.CharField(choices=[('ACTIVE', 'Действующий'), ('LIQUIDATING', 'Ликвидируется'), ('LIQUIDATED', 'Ликвидирован'), ('BANKRUPT', 'Банкротство'), ('REORGANIZING', 'Реорганизация'), ('NA', 'Нет данных')], db_index=True, default='NA', max_length=30, verbose_name='Статус')),
                ('ba', models.JSONField(blank=True, default=list, null=True, verbose_name='Банковские счета')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено из источника')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
    ]
