# Generated by Django 6.1 on 2026-09-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные'),
        ),
    ]
