# Generated by Django 6.1 on 2026-09-14 23:35

import cp.models.cp_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_cp_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа контрагентов',
                'verbose_name_plural': 'Группы контрагентов',
                'db_table': 'cp_groups',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cp',
            name='ba',
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер счёта')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк')),
                ('bank_bic', models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name='БИК банка')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar/', validators=[cp.models.cp_model.validate_svg], verbose_name='Логотип банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='cp.cp', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
                'db_table': 'bank_accounts',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='cp',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='cps', to='cp.cpgroup', verbose_name='Группы'),
        ),
    ]
