# Generated by Django 6.1 on 2026-09-15 00:11

import cp.models.cp_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_cpgroup_remove_cp_ba_bankaccount_cp_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='БИК')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar/', validators=[cp.models.cp_model.validate_svg], verbose_name='Логотип банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_bic',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='cpgroup',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/', validators=[cp.models.cp_model.validate_svg], verbose_name='Иконка группы'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='cp.bank', verbose_name='Банк (БИК)'),
        ),
    ]
