# Generated by Django 6.1 on 2026-09-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0004_bank_remove_bankaccount_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='Детали'),
        ),
    ]
