# Generated by Django 6.1 on 2026-09-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0005_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpgroup',
            name='name',
            field=models.CharField(choices=[('GROUP', 'Группа'), ('SHAREHOLDER', 'Акционер'), ('RELATED', 'Аффилированное лицо'), ('BANK', 'Банк'), ('STATE', 'Государственный орган'), ('CONTRACTOR', 'Подрядчик'), ('CUSTOMER', 'Покупатель'), ('LENDER', 'Займодавец'), ('BORROWER', 'Заёмщик'), ('EMPLOYEE', 'Сотрудник')], max_length=20, unique=True, verbose_name='Группа'),
        ),
    ]
