# Generated by Django 6.1 on 2026-09-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0006_alter_cpgroup_name'),
        ('macro', '0002_fx_numeric_code_alter_fx_code_alter_fx_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bic',
            field=models.ForeignKey(blank=True, db_column='bic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='cp.bank', to_field='bic', verbose_name='Банк (БИК)'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeric_code_currency', to='macro.fx', to_field='numeric_code', verbose_name='Валюта'),
        ),
    ]
