# Generated by Django 6.1 on 2026-09-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0007_alter_bankaccount_bic_alter_bankaccount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPGroupCompany',
            fields=[
            ],
            options={
                'verbose_name': 'Компания группы',
                'verbose_name_plural': 'Компании группы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cp.cp',),
        ),
    ]
